module.exports = { 
	// devtools:{
	// 	remote:true
	// },
	h5: {  
		//url:'http://localhost:8082',
		options: {
			headless: false  
		}
	}
}

let tjson={
  globalConfig: {
    bail: 0,
    changedFilesWithAncestor: false,
    changedSince: undefined,
    ci: false,
    collectCoverage: false,
    collectCoverageFrom: [],
    coverageDirectory: 'D:\\50.code\\uniapp\\vue2\\coverage',
    coverageProvider: 'babel',
    coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
    coverageThreshold: undefined,
    detectLeaks: false,
    detectOpenHandles: false,
    errorOnDeprecated: false,
    expand: false,
    filter: undefined,
    findRelatedTests: false,
    forceExit: true,
    globalSetup: undefined,
    globalTeardown: 'D:\\50.code\\uniapp\\vue2\\node_modules\\@dcloudio\\uni-automator\\dist\\teardown.js',
    json: false,
    lastCommit: false,
    listTests: false,
    logHeapUsage: false,
    maxConcurrency: 5,
    maxWorkers: 1,
    noSCM: undefined,
    noStackTrace: false,
    nonFlagArgs: [],
    notify: false,
    notifyMode: 'failure-change',
    onlyChanged: false,
    onlyFailures: false,
    outputFile: undefined,
    passWithNoTests: false,
    projects: [],
    replname: undefined,
    reporters: [ [Array] ],
    rootDir: 'D:\\50.code\\uniapp\\vue2',
    runTestsByPath: false,
    shard: undefined,
    silent: undefined,
    skipFilter: false,
    snapshotFormat: { escapeString: false, printBasicPrototype: false },
    testFailureExitCode: 1,
    testNamePattern: undefined,
    testPathPattern: '',
    testResultsProcessor: undefined,
    testSequencer: 'D:\\50.code\\uniapp\\vue2\\node_modules\\@jest\\test-sequencer\\build\\index.js',
    testTimeout: 15000,
    updateSnapshot: 'new',
    useStderr: false,
    verbose: true,
    watch: false,
    watchAll: false,
    watchPlugins: undefined,
    watchman: true,
    workerIdleMemoryLimit: undefined
  },
  projectConfig: {
    automock: false,
    cache: true,
    cacheDirectory: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\jest',
    clearMocks: false,
    coveragePathIgnorePatterns: [ '\\\\node_modules\\\\' ],
    cwd: 'D:\\50.code\\uniapp\\vue2',
    dependencyExtractor: undefined,
    detectLeaks: false,
    detectOpenHandles: false,
    displayName: undefined,
    errorOnDeprecated: false,
    extensionsToTreatAsEsm: [],
    fakeTimers: { enableGlobally: false },
    filter: undefined,
    forceCoverageMatch: [],
    globalSetup: undefined,
    globalTeardown: 'D:\\50.code\\uniapp\\vue2\\node_modules\\@dcloudio\\uni-automator\\dist\\teardown.js',
    globals: {},
    haste: {
      computeSha1: false,
      enableSymlinks: false,
      forceNodeFilesystemAPI: true,
      throwOnModuleCollision: false
    },
    id: 'b1ec424bcfb2fa1b4c82adc5d47425e0',
    injectGlobals: true,
    moduleDirectories: [ 'node_modules' ],
    moduleFileExtensions: [ 'js', 'json' ],
    moduleNameMapper: [],
    modulePathIgnorePatterns: [],
    modulePaths: undefined,
    prettierPath: 'prettier',
    resetMocks: false,
    resetModules: false,
    resolver: undefined,
    restoreMocks: false,
    rootDir: 'D:\\50.code\\uniapp\\vue2',
    roots: [ 'D:\\50.code\\uniapp\\vue2' ],
    runner: 'D:\\50.code\\uniapp\\vue2\\node_modules\\jest-runner\\build\\index.js',
    runtime: undefined,
    sandboxInjectedGlobals: [],
    setupFiles: [],
    setupFilesAfterEnv: [],
    skipFilter: false,
    skipNodeResolution: undefined,
    slowTestThreshold: 5,
    snapshotFormat: { escapeString: false, printBasicPrototype: false },
    snapshotResolver: undefined,
    snapshotSerializers: [],
    testEnvironment: 'D:\\50.code\\uniapp\\vue2\\node_modules\\@dcloudio\\uni-automator\\dist\\environment.js',
    testEnvironmentOptions: { h5: [Object] },
    testLocationInResults: false,
    testMatch: [ 'D:/50.code/uniapp/vue2/src/**/*test.[jt]s?(x)' ],
    testPathIgnorePatterns: [ '\\\\node_modules\\\\' ],
    testRegex: [],
    testRunner: 'D:\\50.code\\uniapp\\vue2\\node_modules\\jest-circus\\runner.js',
    transform: [ [Array] ],
    transformIgnorePatterns: [ '\\\\node_modules\\\\', '\\.pnp\\.[^\\\\]+$' ],
    unmockedModulePathPatterns: undefined,
    watchPathIgnorePatterns: [ '\\\\node_modules\\\\', '\\\\dist\\\\', '\\\\.git\\\\' ]
  }
}